/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SchemaJson {
  metadata: {
    width: number;
    height: number;
    positiveCoord: {
      xRight: boolean;
      yDown: boolean;
      [k: string]: any;
    };
    [k: string]: any;
  };
  scene: Node[];
  [k: string]: any;
}
export interface Node {
  id: string;
  name: string;
  constructorName: string;
  transform: Transform;
  spine?: Spine;
  sprite?: Sprite;
  text?: Text;
  [k: string]: any;
}
export interface Transform {
  width?: number;
  height?: number;
  x: number;
  y: number;
  anchor: {
    x: number;
    y: number;
    [k: string]: any;
  };
  parent?: string;
  children?: string[];
  [k: string]: any;
}
export interface Spine {
  url: string;
  skin: string;
  animation?: {
    name: string;
    loop?: boolean;
    offset?: number;
    [k: string]: any;
  };
  [k: string]: any;
}
export interface Sprite {
  url?: string;
  base64?: string;
  [k: string]: any;
}
export interface Text {
  text: string;
  style: {
    size?: number;
    color?: string;
    [k: string]: any;
  };
  [k: string]: any;
}
