/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DefinitionsNodeJson {
  [k: string]: any;
}
/**
 * This interface was referenced by `DefinitionsNodeJson`'s JSON-Schema
 * via the `definition` "Node".
 */
export interface Node {
  id: string;
  name: string;
  constructor: string;
  transform: Transform;
  spine?: Spine;
  sprite?: Sprite;
  text?: Text;
  [k: string]: any;
}
export interface Transform {
  x: number;
  y: number;
  parent?: string;
  children?: string[];
  [k: string]: any;
}
export interface Spine {
  url: string;
  skin: string;
  animation?: {
    name: string;
    loop?: boolean;
    offset?: number;
    [k: string]: any;
  };
  [k: string]: any;
}
export interface Sprite {
  url?: string;
  base64?: string;
  [k: string]: any;
}
export interface Text {
  text: string;
  style: {
    size?: number;
    color?: string;
    [k: string]: any;
  };
  [k: string]: any;
}
